version: '3.8'

services:
  # Ollama service for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: manju-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "test -f /bin/ollama && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Uncomment below lines if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Voice Chatbot application
  voice-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manju-voice-chatbot
    ports:
      - "8501:8501"
    volumes:
      - ./audio_uploads:/app/audio_uploads
      - ./results:/app/results
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama model downloader (init container)
  ollama-setup:
    image: ollama/ollama:latest
    container_name: manju-ollama-setup
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    command: ["ollama", "pull", "phi3"]
    restart: "no"

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: manju-network
